<template>
  <vs-popup title="Icon Picker" :active.sync="popupActive">
    <vs-input v-model="search" name="search" v-shortkey.focus="['alt', 'f']" />
    <!-- <vs-button
        type="border"
        icon-pack="feather"
        class="m-1"
        color="dark"
        size="large"
        :key="icon"
        :icon="'icon-' + icon"
      ></vs-button> -->
    <div class="flex w-full flex-wrap">
      <!-- <vs-button
        v-for="icon in iconList"
        type="border"
        icon-pack="feather"
        class="m-1"
        color="dark"
        size="large"
        :key="icon"
        :icon="'icon-' + icon"
      ></vs-button> -->
      <vs-button
        type="border"
        class="m-1"
        color="dark"
        v-for="icon in listIconFiltered"
        :key="icon"
        @click="setIcon(icon)"
      >
        <feather-icon :icon="icon" />
      </vs-button>
    </div>
  </vs-popup>
</template>
<script>
export default {
  name: "IconPickerPopup",
  computed: {
    listIconFiltered() {
      return this.iconList.filter((t) =>
        this.search == "" ? true : t.toLowerCase().match(this.search.toLowerCase())
      );
    },
  },
  data() {
    return {
      search: "",
      popupActive: false,
      iconList: [
        "ActivityIcon",
        "AirplayIcon",
        "AlertCircleIcon",
        "AlertOctagonIcon",
        "AlertTriangleIcon",
        "AlignCenterIcon",
        "AlignJustifyIcon",
        "AlignLeftIcon",
        "AlignRightIcon",
        "AnchorIcon",
        "ApertureIcon",
        "ArchiveIcon",
        "ArrowDownIcon",
        "ArrowDownCircleIcon",
        "ArrowDownLeftIcon",
        "ArrowDownRightIcon",
        "ArrowLeftIcon",
        "ArrowLeftCircleIcon",
        "ArrowRightIcon",
        "ArrowRightCircleIcon",
        "ArrowUpIcon",
        "ArrowUpCircleIcon",
        "ArrowUpLeftIcon",
        "ArrowUpRightIcon",
        "AtSignIcon",
        "AwardIcon",
        "BarChartIcon",
        "BarChart2Icon",
        "BatteryIcon",
        "BatteryChargingIcon",
        "BellIcon",
        "BellOffIcon",
        "BluetoothIcon",
        "BoldIcon",
        "BookIcon",
        "BookOpenIcon",
        "BookmarkIcon",
        "BoxIcon",
        "BriefcaseIcon",
        "CalendarIcon",
        "CameraIcon",
        "CameraOffIcon",
        "CastIcon",
        "CheckIcon",
        "CheckCircleIcon",
        "CheckSquareIcon",
        "ChevronDownIcon",
        "ChevronLeftIcon",
        "ChevronRightIcon",
        "ChevronUpIcon",
        "ChevronsDownIcon",
        "ChevronsLeftIcon",
        "ChevronsRightIcon",
        "ChevronsUpIcon",
        "ChromeIcon",
        "CircleIcon",
        "ClipboardIcon",
        "ClockIcon",
        "CloudIcon",
        "CloudDrizzleIcon",
        "CloudLightningIcon",
        "CloudOffIcon",
        "CloudRainIcon",
        "CloudSnowIcon",
        "CodeIcon",
        "CodepenIcon",
        "CodesandboxIcon",
        "CoffeeIcon",
        "ColumnsIcon",
        "CommandIcon",
        "CompassIcon",
        "CopyIcon",
        "CornerDownLeftIcon",
        "CornerDownRightIcon",
        "CornerLeftDownIcon",
        "CornerLeftUpIcon",
        "CornerRightDownIcon",
        "CornerRightUpIcon",
        "CornerUpLeftIcon",
        "CornerUpRightIcon",
        "CpuIcon",
        "CreditCardIcon",
        "CropIcon",
        "CrosshairIcon",
        "DatabaseIcon",
        "DeleteIcon",
        "DiscIcon",
        "DivideIcon",
        "DivideCircleIcon",
        "DivideSquareIcon",
        "DollarSignIcon",
        "DownloadIcon",
        "DownloadCloudIcon",
        "DribbbleIcon",
        "DropletIcon",
        "EditIcon",
        "Edit2Icon",
        "Edit3Icon",
        "ExternalLinkIcon",
        "EyeIcon",
        "EyeOffIcon",
        "FacebookIcon",
        "FastForwardIcon",
        "FeatherIcon",
        "FigmaIcon",
        "FileIcon",
        "FileMinusIcon",
        "FilePlusIcon",
        "FileTextIcon",
        "FilmIcon",
        "FilterIcon",
        "FlagIcon",
        "FolderIcon",
        "FolderMinusIcon",
        "FolderPlusIcon",
        "FramerIcon",
        "FrownIcon",
        "GiftIcon",
        "GitBranchIcon",
        "GitCommitIcon",
        "GitMergeIcon",
        "GitPullRequestIcon",
        "GithubIcon",
        "GitlabIcon",
        "GlobeIcon",
        "GridIcon",
        "HardDriveIcon",
        "HashIcon",
        "HeadphonesIcon",
        "HeartIcon",
        "HelpCircleIcon",
        "HexagonIcon",
        "HomeIcon",
        "ImageIcon",
        "InboxIcon",
        "InfoIcon",
        "InstagramIcon",
        "ItalicIcon",
        "KeyIcon",
        "LayersIcon",
        "LayoutIcon",
        "LifeBuoyIcon",
        "LinkIcon",
        "Link2Icon",
        "LinkedinIcon",
        "ListIcon",
        "LoaderIcon",
        "LockIcon",
        "LogInIcon",
        "LogOutIcon",
        "MailIcon",
        "MapIcon",
        "MapPinIcon",
        "MaximizeIcon",
        "Maximize2Icon",
        "MehIcon",
        "MenuIcon",
        "MessageCircleIcon",
        "MessageSquareIcon",
        "MicIcon",
        "MicOffIcon",
        "MinimizeIcon",
        "Minimize2Icon",
        "MinusIcon",
        "MinusCircleIcon",
        "MinusSquareIcon",
        "MonitorIcon",
        "MoonIcon",
        "MoreHorizontalIcon",
        "MoreVerticalIcon",
        "MousePointerIcon",
        "MoveIcon",
        "MusicIcon",
        "NavigationIcon",
        "Navigation2Icon",
        "OctagonIcon",
        "PackageIcon",
        "PaperclipIcon",
        "PauseIcon",
        "PauseCircleIcon",
        "PenToolIcon",
        "PercentIcon",
        "PhoneIcon",
        "PhoneCallIcon",
        "PhoneForwardedIcon",
        "PhoneIncomingIcon",
        "PhoneMissedIcon",
        "PhoneOffIcon",
        "PhoneOutgoingIcon",
        "PieChartIcon",
        "PlayIcon",
        "PlayCircleIcon",
        "PlusIcon",
        "PlusCircleIcon",
        "PlusSquareIcon",
        "PocketIcon",
        "PowerIcon",
        "PrinterIcon",
        "RadioIcon",
        "RefreshCcwIcon",
        "RefreshCwIcon",
        "RepeatIcon",
        "RewindIcon",
        "RotateCcwIcon",
        "RotateCwIcon",
        "RssIcon",
        "SaveIcon",
        "ScissorsIcon",
        "SearchIcon",
        "SendIcon",
        "ServerIcon",
        "SettingsIcon",
        "ShareIcon",
        "Share2Icon",
        "ShieldIcon",
        "ShieldOffIcon",
        "ShoppingBagIcon",
        "ShoppingCartIcon",
        "ShuffleIcon",
        "SidebarIcon",
        "SkipBackIcon",
        "SkipForwardIcon",
        "SlackIcon",
        "SlashIcon",
        "SlidersIcon",
        "SmartphoneIcon",
        "SmileIcon",
        "SpeakerIcon",
        "SquareIcon",
        "StarIcon",
        "StopCircleIcon",
        "SunIcon",
        "SunriseIcon",
        "SunsetIcon",
        "TabletIcon",
        "TagIcon",
        "TargetIcon",
        "TerminalIcon",
        "ThermometerIcon",
        "ThumbsDownIcon",
        "ThumbsUpIcon",
        "ToggleLeftIcon",
        "ToggleRightIcon",
        "ToolIcon",
        "TrashIcon",
        "Trash2Icon",
        "TrelloIcon",
        "TrendingDownIcon",
        "TrendingUpIcon",
        "TriangleIcon",
        "TruckIcon",
        "TvIcon",
        "TwitchIcon",
        "TwitterIcon",
        "TypeIcon",
        "UmbrellaIcon",
        "UnderlineIcon",
        "UnlockIcon",
        "UploadIcon",
        "UploadCloudIcon",
        "UserIcon",
        "UserCheckIcon",
        "UserMinusIcon",
        "UserPlusIcon",
        "UserXIcon",
        "UsersIcon",
        "VideoIcon",
        "VideoOffIcon",
        "VoicemailIcon",
        "VolumeIcon",
        "Volume1Icon",
        "Volume2Icon",
        "VolumeXIcon",
        "WatchIcon",
        "WifiIcon",
        "WifiOffIcon",
        "WindIcon",
        "XIcon",
        "XCircleIcon",
        "XOctagonIcon",
        "XSquareIcon",
        "YoutubeIcon",
        "ZapIcon",
        "ZapOffIcon",
        "ZoomInIcon",
        "ZoomOutIcon",
      ],
    };
  },
  watch: {
    popupActive(newval) {
      if (!newval) {
        this.reset();
      } else {
        setTimeout(() => {
          this.focus();
        }, 1000);
      }
    },
  },
  methods: {
    setIcon(icon) {
      this.$emit('setIcon', icon);
      this.close();
    },
    focus() {
      this.$el.querySelector('input[name=search]').focus();
    },
    open() {
      this.popupActive = true;
    },
    close() {
      this.popupActive = false;
    },
    toggle() {
      this.popupActive = !this.popupActive;
    },
    reset() {},
  },
};
</script>
